### PR TITLE
Initial commit

### PR DESCRIPTION
**Pull request by andreikasmykou**
Sorry for delay

PR cart-service: https://github.com/Raerka/rs-cart-api/pull/1 
Description can be found there

 5 - FE application is updated with Cart API endpoint. You must provide a PR with updates in your FE repository and OPTIONALLY link to deployed front-end app which makes proper API calls to your Cart service

Link to the deployed Cart API Service: http://raerka-cart-api.eu-west-1.elasticbeanstalk.com/ 
Link to the deployed Application: https://d17q5m0kik9x1l.cloudfront.net/

Expected score 5/5

### CODE REVIEW

**Review by OHalahan — COMMENTED** [review]
joining for getting updates

**Comment by IDiamondDragon** [comment]
Hello, Are you going to deploy this work Task 8 (Docker. AWS Elastic Beanstalk)?

**Comment by andreikasmykou** [comment]
All changes were made
Again sorry for delay

**Comment by IDiamondDragon** [comment]
Okay. No problems.

**Comment by MariiaTarasiuk** [comment]
could you plz provide a link to cart-api PR?

**Comment by andreikasmykou** [comment]
Yes, it is also in the description section
PR cart-service: Raerka/rs-cart-api#1

**Pull request merged**
